### ISSUE TITLE
Getting CrashLoopBackOff with config: ReadFile failed on /etc/consul/..data: read /etc/consul/..data: is a directory

### ISSUE THREAD

**Issue by mickengland** [drud/vault-consul-on-kube#23]
## What happened (or feature request):
Consul pods are failing with CrashLoopBackOff and config: ReadFile failed on /etc/consul/..data: read /etc/consul/..data: is a directory in the logs.

## What you expected to happen:
Consul pods to come up normally.

## How to reproduce it (as minimally and precisely as possible):
```
kubectl apply -f deployments/consul-1.yaml -f deployments/consul-2.yaml -f deployments/consul-3.yaml
```

## Anything else do we need to know:
I am attempting to get this going on AWS so a few things are changed in terms of volume mounts. Here is my current config:
```
volumeMounts:
            - name: data
              mountPath: "/var/lib/consul"
              name: data
            - name: consulconfig
              mountPath: "/etc/consul"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-consul-1
        - name: consulconfig
          secret:
            secretName: consul-config
```
```
$> kubectl get pv
NAME                    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                        STORAGECLASS   REASON    AGE
consul-1                50Gi       RWO            Retain           Bound     default/pvc-consul-1                                  1h
consul-2                50Gi       RWO            Retain           Bound     default/pvc-consul-2                                  1h
consul-3                50Gi       RWO            Retain           Bound     default/pvc-consul-3                                  1h
```
```
$> kubectl get pvc
pvc-consul-1         Bound     consul-1                50Gi       RWO                           1h
pvc-consul-2         Bound     consul-2                50Gi       RWO                           1h
pvc-consul-3         Bound     consul-3                50Gi       RWO                           1h
```
I have three EBS volumes, on in each availability zone of my kubernetes hosts and the pvc references the correct one for the AZ. Any pointers on how to troubleshoot this?

## Related source links or issues:
